package mx.com.adesis.jsonschema.test;

public class JsonSchemaString {
	public static final String JSON_SCHEMA_AS_STRING = "{"
			+ "	\"type\": \"object\","
			+ "	\"$schema\": \"#un-schema\","
			+ "	\"id\": \"ContractDocument\","
			+ "	\"description\": \"Contrato de cliente con BBVA\","
			+ "	\"required\": [ \"documentFile\", \"options\", \"options2\" ],"
			+ "	\"properties\": {"
			+ "		\"version\": {"
			+ "			\"type\": \"string\","
			+ "			\"description\": \"Versión del contrato\","
			+ "			\"readonly\": true"
			+ "		},"
			+ "		\"version2\": {"
			+ "			\"type\": \"string\","
			+ "			\"description\": \"Versión del contrato\","
			+ "			\"readonly\": true"
			+ "		},"
			+ "		\"sexo\": {"
			+ "			\"enum\": [ \"MASCULINO\", \"FEMENINO\" ],"
			+ "			\"description\": \"Sexo del contrato\","
			+ "			\"readonly\": false"
			+ "		},"
			+ "		\"product\": {"
			+ "			\"oneOf\": ["
			+ "				{ \"$ref\": \"account\" },"
			+ "				{ \"$ref\": \"card\" },"
			+ "				{ \"$ref\": \"investments\" },"
			+ "				{ \"$ref\": \"loan\" },"
			+ "				{ \"$ref\": \"scrow\" },"
			+ "				{ \"$ref\": \"heritage\" }"
			+ "			]"
			+ "		},"
			+ "		\"server\": {"
			+ "			\"type\": \"string\","
			+ "			\"oneOf\": ["
			+ "				{ \"format\": \"host-name\" },"
			+ "				{ \"format\": \"ipv4\" },"
			+ "				{ \"format\": \"ipv6\" }"
			+ "			]"
			+ "		},"
			+ "		\"options\": {"
			+ "			\"type\": \"array\","
			+ "			\"minItems\": 1,"
			+ "			\"items\": {"
			+ "				\"type\": \"string\","
			+ "				\"description\": \"Descripcin del Item\""
			+ "			},"
			+ "			\"uniqueItems\": true"
			+ "		},"
			+ "		\"participants\": {"
			+ "			\"type\": \"array\","
			+ "			\"minItems\": 2,"
			+ "			\"description\": \"Listado de participantes del contrato.\","
			+ "			\"items\": {"
			+ "				\"type\": \"string\","
			+ "				\"$ref\": \"participant\","
			+ "				\"description\": \"Descripción del Item\""
			+ "			},"
			+ "			\"uniqueItems\": true"
			+ "		},"
			+ "		\"documentFile\": {"
			+ "			\"$ref\": \"documentFile\","
			+ "			\"description\": \"Datos del archivo del contrato\","
			+ "			\"readonly\": true"
			+ "		}"
			+ "	}"
			+ "}";
}
